name = "plinko-prediction-fr"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=plinko-prediction.fr"
HMAC_KEY = "35604fa8d5e8ca13626caaf257854b5c050292d941dbe3757112812676e2ec50"
COOKIE_NAME = "4gd"
PLAY_PATH = "start-now"
BUTTON_ID = "p440df35fda2864641ae404607f811334"
GATE_SALT = "5bf53fdbaf087b73"
